// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: testing/node_testing.proto

package node_testing

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LOP     int64  `protobuf:"varint,1,opt,name=LOP,proto3" json:"LOP,omitempty"`
	ROP     int64  `protobuf:"varint,2,opt,name=ROP,proto3" json:"ROP,omitempty"`
	DataStr string `protobuf:"bytes,3,opt,name=DataStr,proto3" json:"DataStr,omitempty"`
}

func (x *SumReq) Reset() {
	*x = SumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testing_node_testing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumReq) ProtoMessage() {}

func (x *SumReq) ProtoReflect() protoreflect.Message {
	mi := &file_testing_node_testing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumReq.ProtoReflect.Descriptor instead.
func (*SumReq) Descriptor() ([]byte, []int) {
	return file_testing_node_testing_proto_rawDescGZIP(), []int{0}
}

func (x *SumReq) GetLOP() int64 {
	if x != nil {
		return x.LOP
	}
	return 0
}

func (x *SumReq) GetROP() int64 {
	if x != nil {
		return x.ROP
	}
	return 0
}

func (x *SumReq) GetDataStr() string {
	if x != nil {
		return x.DataStr
	}
	return ""
}

type SumRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int64 `protobuf:"varint,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
}

func (x *SumRes) Reset() {
	*x = SumRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testing_node_testing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRes) ProtoMessage() {}

func (x *SumRes) ProtoReflect() protoreflect.Message {
	mi := &file_testing_node_testing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRes.ProtoReflect.Descriptor instead.
func (*SumRes) Descriptor() ([]byte, []int) {
	return file_testing_node_testing_proto_rawDescGZIP(), []int{1}
}

func (x *SumRes) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_testing_node_testing_proto protoreflect.FileDescriptor

var file_testing_node_testing_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x06,
	0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x4f, 0x50, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x4c, 0x4f, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x4f, 0x50, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x52, 0x4f, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x74, 0x72, 0x22, 0x1a, 0x0a, 0x06, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x53, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x53, 0x75, 0x6d,
	0x42, 0x13, 0x5a, 0x11, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testing_node_testing_proto_rawDescOnce sync.Once
	file_testing_node_testing_proto_rawDescData = file_testing_node_testing_proto_rawDesc
)

func file_testing_node_testing_proto_rawDescGZIP() []byte {
	file_testing_node_testing_proto_rawDescOnce.Do(func() {
		file_testing_node_testing_proto_rawDescData = protoimpl.X.CompressGZIP(file_testing_node_testing_proto_rawDescData)
	})
	return file_testing_node_testing_proto_rawDescData
}

var file_testing_node_testing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testing_node_testing_proto_goTypes = []interface{}{
	(*SumReq)(nil), // 0: SumReq
	(*SumRes)(nil), // 1: SumRes
}
var file_testing_node_testing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testing_node_testing_proto_init() }
func file_testing_node_testing_proto_init() {
	if File_testing_node_testing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testing_node_testing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testing_node_testing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testing_node_testing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testing_node_testing_proto_goTypes,
		DependencyIndexes: file_testing_node_testing_proto_depIdxs,
		MessageInfos:      file_testing_node_testing_proto_msgTypes,
	}.Build()
	File_testing_node_testing_proto = out.File
	file_testing_node_testing_proto_rawDesc = nil
	file_testing_node_testing_proto_goTypes = nil
	file_testing_node_testing_proto_depIdxs = nil
}
